clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 14 2015 Win64"
      QTDIR: C:\Qt\5.6.3\msvc2015_64
      PLATFORM: x64
    - GENERATOR : "Visual Studio 14 2015"
      QTDIR: C:\Qt\5.6.3\msvc2015
      PLATFORM: Win32

image: Visual Studio 2015

configuration:
  - Release

install:
  - set PATH=%QTDIR%\bin;%PATH%
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0;%PATH%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin=% # trick to remove sh.exe

before_build:
  - mkdir build
  - cd build
  - mkdir bin
  - set OUTPUT_DIR=%cd%\bin
  - cmake "-G%GENERATOR%"
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG="%OUTPUT_DIR%"
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE="%OUTPUT_DIR%"
    -DCMAKE_CXX_FLAGS_INIT="%CMAKE_CXX_FLAGS_INIT%"
    ..


build_script:
  - cmake --build .

test_script:
  - ctest --output-on-failure -C Debug
